#!/bin/bash

# Script completo para probar el sistema micro-ROS

BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

clear
echo -e "${CYAN}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║                                                           ║${NC}"
echo -e "${CYAN}║       🚀 GUÍA COMPLETA - micro-ROS ESP32 🚀              ║${NC}"
echo -e "${CYAN}║                                                           ║${NC}"
echo -e "${CYAN}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""

echo -e "${YELLOW}┌─────────────────────────────────────────────────────────┐${NC}"
echo -e "${YELLOW}│  ESTADO DEL PROYECTO                                    │${NC}"
echo -e "${YELLOW}└─────────────────────────────────────────────────────────┘${NC}"
echo ""
echo -e "  ${GREEN}✓${NC} Código modificado para funcionar como nodo ROS"
echo -e "  ${GREEN}✓${NC} Compilación exitosa (sin errores)"
echo -e "  ${GREEN}✓${NC} Sensor DS18B20 integrado"
echo -e "  ${GREEN}✓${NC} micro-ROS configurado"
echo ""

echo -e "${YELLOW}┌─────────────────────────────────────────────────────────┐${NC}"
echo -e "${YELLOW}│  QUÉ HACE TU ESP32 AHORA                                │${NC}"
echo -e "${YELLOW}└─────────────────────────────────────────────────────────┘${NC}"
echo ""
echo -e "  📡 Actúa como un ${CYAN}nodo ROS 2${NC} completo"
echo -e "  🌡️  Lee temperatura del sensor DS18B20"
echo -e "  📊 Publica en el tópico ${CYAN}/temperatura${NC} cada 2 segundos"
echo -e "  🔌 Se comunica con el PC vía USB Serial"
echo -e "  🤖 Compatible con todo el ecosistema ROS 2"
echo ""

echo -e "${YELLOW}┌─────────────────────────────────────────────────────────┐${NC}"
echo -e "${YELLOW}│  PASO 1: FLASHEAR EL ESP32                             │${NC}"
echo -e "${YELLOW}└─────────────────────────────────────────────────────────┘${NC}"
echo ""
echo -e "  Opción A - Script automático:"
echo -e "    ${BLUE}./build_and_flash.sh${NC}"
echo ""
echo -e "  Opción B - Manual:"
echo -e "    ${BLUE}source /home/lab-ros/esp/v5.5.2/esp-idf/export.sh${NC}"
echo -e "    ${BLUE}idf.py build flash monitor${NC}"
echo ""

echo -e "${YELLOW}┌─────────────────────────────────────────────────────────┐${NC}"
echo -e "${YELLOW}│  PASO 2: INSTALAR micro-ROS AGENT (solo una vez)       │${NC}"
echo -e "${YELLOW}└─────────────────────────────────────────────────────────┘${NC}"
echo ""
echo -e "    ${BLUE}./install_microros_agent.sh${NC}"
echo ""
echo -e "  O manualmente:"
echo -e "    ${BLUE}sudo apt install ros-jazzy-micro-ros-agent${NC}"
echo ""

echo -e "${YELLOW}┌─────────────────────────────────────────────────────────┐${NC}"
echo -e "${YELLOW}│  PASO 3: INICIAR EL AGENT (Terminal 1)                 │${NC}"
echo -e "${YELLOW}└─────────────────────────────────────────────────────────┘${NC}"
echo ""
echo -e "    ${BLUE}source /opt/ros/jazzy/setup.bash${NC}"
echo -e "    ${BLUE}ros2 run micro_ros_agent micro_ros_agent serial \\${NC}"
echo -e "    ${BLUE}         --dev /dev/ttyUSB0 -b 115200${NC}"
echo ""
echo -e "  ${GREEN}Cuando veas:${NC} \"✅ Conectado al micro-ROS Agent!\""
echo -e "  ${GREEN}Significa que${NC} el ESP32 y el PC están comunicados"
echo ""

echo -e "${YELLOW}┌─────────────────────────────────────────────────────────┐${NC}"
echo -e "${YELLOW}│  PASO 4: VER DATOS ROS (Terminal 2)                    │${NC}"
echo -e "${YELLOW}└─────────────────────────────────────────────────────────┘${NC}"
echo ""
echo -e "    ${BLUE}source /opt/ros/jazzy/setup.bash${NC}"
echo ""
echo -e "  Ver nodos:"
echo -e "    ${BLUE}ros2 node list${NC}"
echo -e "    ${GREEN}→ /esp32_temp_sensor${NC}"
echo ""
echo -e "  Ver tópicos:"
echo -e "    ${BLUE}ros2 topic list${NC}"
echo -e "    ${GREEN}→ /temperatura${NC}"
echo ""
echo -e "  Escuchar temperatura:"
echo -e "    ${BLUE}ros2 topic echo /temperatura${NC}"
echo -e "    ${GREEN}→ data: 25.31${NC}"
echo -e "    ${GREEN}→ ---${NC}"
echo -e "    ${GREEN}→ data: 25.25${NC}"
echo ""
echo -e "  Ver frecuencia:"
echo -e "    ${BLUE}ros2 topic hz /temperatura${NC}"
echo -e "    ${GREEN}→ average rate: 0.500 (cada 2 segundos)${NC}"
echo ""

echo -e "${YELLOW}┌─────────────────────────────────────────────────────────┐${NC}"
echo -e "${YELLOW}│  ARQUITECTURA DEL SISTEMA                               │${NC}"
echo -e "${YELLOW}└─────────────────────────────────────────────────────────┘${NC}"
echo ""
echo "     ┌────────────┐    Serial USB     ┌──────────────┐"
echo "     │   ESP32    │ ←────────────────→│ micro-ROS    │"
echo "     │  (Nodo ROS)│   115200 baud     │   Agent      │"
echo "     │            │                   │  (Puente)    │"
echo "     │ DS18B20    │                   └──────┬───────┘"
echo "     │ Sensor     │                          │"
echo "     │ 25.31°C    │                      DDS/UDP"
echo "     │            │                          │"
echo "     │ Publica:   │                          ▼"
echo "     │/temperatura│                   ┌──────────────┐"
echo "     └────────────┘                   │  ROS 2 PC    │"
echo "                                      │  (Jazzy)     │"
echo "                                      │              │"
echo "                                      │ • Nodos      │"
echo "                                      │ • rqt_plot   │"
echo "                                      │ • rviz2      │"
echo "                                      └──────────────┘"
echo ""

echo -e "${YELLOW}┌─────────────────────────────────────────────────────────┐${NC}"
echo -e "${YELLOW}│  HERRAMIENTAS DISPONIBLES                               │${NC}"
echo -e "${YELLOW}└─────────────────────────────────────────────────────────┘${NC}"
echo ""
echo -e "  📝 ${CYAN}README.md${NC} - Documentación completa"
echo -e "  🚀 ${CYAN}QUICKSTART.md${NC} - Inicio rápido (5 minutos)"
echo -e "  📊 ${CYAN}USO_NODO_ROS.md${NC} - Guía detallada del nodo ROS"
echo -e "  🔧 ${CYAN}build_and_flash.sh${NC} - Compilar y flashear"
echo -e "  🛠️  ${CYAN}microros_helper.sh${NC} - Menú interactivo"
echo -e "  📦 ${CYAN}install_microros_agent.sh${NC} - Instalar agent"
echo ""

echo -e "${YELLOW}┌─────────────────────────────────────────────────────────┐${NC}"
echo -e "${YELLOW}│  SOLUCIÓN DE PROBLEMAS                                  │${NC}"
echo -e "${YELLOW}└─────────────────────────────────────────────────────────┘${NC}"
echo ""
echo -e "  ${RED}No detecta sensor:${NC}"
echo -e "    • Verificar conexiones físicas"
echo -e "    • Verificar resistencia pull-up 4.7kΩ"
echo ""
echo -e "  ${RED}No se conecta al Agent:${NC}"
echo -e "    • Verificar que el Agent está corriendo"
echo -e "    • Verificar puerto: ${BLUE}ls /dev/ttyUSB*${NC}"
echo -e "    • Dar permisos: ${BLUE}sudo chmod 666 /dev/ttyUSB0${NC}"
echo ""
echo -e "  ${RED}No aparecen tópicos:${NC}"
echo -e "    • Esperar conexión (ver monitor ESP32)"
echo -e "    • Reiniciar ESP32 (botón RESET)"
echo -e "    • Verificar ROS_DOMAIN_ID=0"
echo ""

echo -e "${GREEN}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                                                           ║${NC}"
echo -e "${GREEN}║   ✅ TU ESP32 YA ES UN NODO ROS PROFESIONAL ✅           ║${NC}"
echo -e "${GREEN}║                                                           ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""

read -p "Presiona Enter para ejecutar el menú interactivo o Ctrl+C para salir..."

# Ejecutar el helper
./scripts/microros_helper.sh
